# Generated by Django 3.1.3 on 2020-12-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('ref1_email', models.CharField(max_length=70)),
                ('ref1_date', models.DateField()),
                ('ref2_email', models.CharField(max_length=70)),
                ('ref2_date', models.DateField()),
                ('ref3_email', models.CharField(max_length=70)),
                ('ref3_date', models.DateField()),
                ('high_frequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=7)),
                ('first_name', models.CharField(max_length=70)),
                ('middle_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=200)),
                ('Gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=7)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('Divorced', 'Divorced'), ('Married', 'Married'), ('Separated', 'Separated'), ('Single', 'Single'), ('Widowed', 'Widowed')], max_length=9)),
                ('country_of_residence', models.CharField(max_length=70)),
                ('state_of_origin', models.CharField(max_length=70)),
                ('LGA', models.CharField(max_length=70)),
                ('state_of_residence', models.CharField(max_length=70)),
                ('LGA_of_residence', models.CharField(max_length=70)),
                ('phone_number', models.IntegerField()),
                ('whatsapp_number', models.IntegerField()),
                ('highest_academic_qualification', models.CharField(choices=[('PhD', 'PhD'), ('Masters', 'Masters'), ('Bachelors, HND or Equivalent', 'Bachelors, HND or Equivalent'), ('OND, NCE or Equivalent', 'OND, NCE or Equivalent'), ('SSCE', 'SSCE'), ('Primary School', 'Primary School'), ('Never attended school', 'Never attended school')], max_length=29)),
                ('current_occupation', models.CharField(choices=[('Artisan/Farmer/Hand-Work', 'Artisan/Farmer/Hand-Work'), ('Civil Servant', 'Civil Servant'), ('Employed (Private Sector/NGO)', 'Employed (Private Sector/NGO)'), ('Entrepreneur/Business Owner', 'Entrepreneur/Business Owner'), ('Unemployed', 'Unemployed'), ('Retired', 'Retired'), ('Never attended school', 'Never attended school')], max_length=29)),
                ('date_of_registration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=5)),
                ('news_title', models.TextField()),
                ('news_short_description', models.CharField(max_length=300)),
                ('news_full_content', models.TextField()),
                ('news_published_on', models.DateField()),
                ('news_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fds_app.newsauthor')),
            ],
        ),
    ]
