# Generated by Django 3.1.3 on 2020-12-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_app', '0005_auto_20201222_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitlist',
            name='ref2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitlist',
            name='ref2_email',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='hitlist',
            name='ref3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitlist',
            name='ref3_email',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='date_of_registration',
            field=models.DateField(default='2020-12-23'),
        ),
    ]
