# Generated by Django 3.1.3 on 2020-12-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_app', '0006_auto_20201223_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date_of_registration',
            field=models.DateField(default='2020-12-24'),
        ),
    ]
