# Generated by Django 3.1.3 on 2021-01-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_app', '0007_auto_20201224_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=200)),
                ('first_name', models.CharField(max_length=70)),
                ('middle_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('amount', models.FloatField(max_length=70)),
                ('payment_type', models.CharField(choices=[('Subscription', 'Subscription'), ('Donation', 'Donation')], max_length=12)),
                ('payment_channel', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('date_of_transaction', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='hitlist',
            name='ref1_email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='hitlist',
            name='ref2_email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='hitlist',
            name='ref3_email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='date_of_registration',
            field=models.DateField(default='2021-01-08'),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
