# Generated by Django 3.1.3 on 2021-01-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_app', '0009_auto_20210108_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date_of_registration',
            field=models.DateField(default='2021-01-10'),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='members',
            name='whatsapp_number',
            field=models.CharField(max_length=16),
        ),
    ]
