# Generated by Django 3.1.3 on 2021-01-14 23:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_app', '0014_auto_20210114_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date_of_registration',
            field=models.DateField(default='2021-01-15'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
