# Generated by Django 3.1.3 on 2021-01-15 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fds_app', '0015_auto_20210115_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_images',
        ),
    ]
