# Generated by Django 3.1.3 on 2021-01-15 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fds_app', '0016_remove_post_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='content',
        ),
    ]
