# Generated by Django 3.1.3 on 2021-01-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds_app', '0017_remove_category_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_extension',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
